// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseDirectory(arg1) {
  return window['go']['main']['App']['BrowseDirectory'](arg1);
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function ShowNotice(arg1, arg2) {
  return window['go']['main']['App']['ShowNotice'](arg1, arg2);
}

export function StartInstallEvents(arg1) {
  return window['go']['main']['App']['StartInstallEvents'](arg1);
}

export function StartLaunchEvents(arg1) {
  return window['go']['main']['App']['StartLaunchEvents'](arg1);
}

export function StartLoaderInstallEvents(arg1) {
  return window['go']['main']['App']['StartLoaderInstallEvents'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
