// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseDirectory(arg1:string):Promise<string>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function ShowNotice(arg1:string,arg2:string):Promise<void>;

export function StartInstallEvents(arg1:string):Promise<void>;

export function StartLaunchEvents(arg1:string):Promise<void>;

export function StartLoaderInstallEvents(arg1:string):Promise<void>;

export function Version():Promise<string>;
